export const articleInfo = [
    {
        ID: 1,
        ARTNO: 12345,
        info: {
            SLoc: 'interior 1',
            SSD: '2012-04-01',
            EDS: '2022-04-01',
            MDQ: 1,
            Stock: 0,
            NextDeliveryDate: '',
            NextDeliveryQty: 0,
            Price: '$890',
            graph: {
                FC: [
                    {wk: 'hist5', value: 1.5},
                    {wk: 'hist4', value: 1.5},
                    {wk: 'hist3', value: 1.5},
                    {wk: 'hist2', value: 1.5},
                    {wk: 'hist1', value: 1.5},
                    {wk: 'wk1', value: 1},
                    {wk: 'wk2', value: 1.5},
                    {wk: 'wk3', value: 2},
                    {wk: 'wk4', value: 1},
                    {wk: 'wk5', value: 0.5},
                ],
                SOLD: [
                    {wk: 'hist5', value: 0},
                    {wk: 'hist4', value: 2},
                    {wk: 'hist3', value: 0},
                    {wk: 'hist2', value: 0},
                    {wk: 'hist1', value: 1},
                    {wk: 'wk1', value: 1},
                    {wk: 'wk2', value: 0},
                    {wk: 'wk3', value: 0},
                    {wk: 'wk4', value: 0},
                    {wk: 'wk5', value: 0},
                ],
            }
        }
    },
    {
        ID: 2,
        ARTNO: 12346,
        info: {
            SLoc: 'shelf 1',
            SSD: '2017-03-01',
            EDS: '',
            MDQ: 50,
            Stock: 20,
            NextDeliveryDate: '2022-04-01',
            NextDeliveryQty: 40,
            Price: '$1',
            graph: {
                FC: [
                    {wk: 'hist5', value: 17},
                    {wk: 'hist4', value: 20},
                    {wk: 'hist3', value: 15},
                    {wk: 'hist2', value: 15},
                    {wk: 'hist1', value: 12},
                    {wk: 'wk1', value: 13},
                    {wk: 'wk2', value: 15},
                    {wk: 'wk3', value: 20},
                    {wk: 'wk4', value: 15},
                    {wk: 'wk5', value: 14},
                ],
                SOLD: [
                    {wk: 'hist5', value: 10},
                    {wk: 'hist4', value: 20},
                    {wk: 'hist3', value: 13},
                    {wk: 'hist2', value: 11},
                    {wk: 'hist1', value: 33},
                    {wk: 'wk1', value: 2},
                    {wk: 'wk2', value: 0},
                    {wk: 'wk3', value: 0},
                    {wk: 'wk4', value: 0},
                    {wk: 'wk5', value: 0},
                ],
            }
        }
    },
    {
        ID: 3,
        ARTNO: 12347,
        info: {
            SLoc: 'shelf 2',
            SSD: '2010-01-01',
            EDS: '',
            MDQ: 1500,
            Stock: 20001,
            NextDeliveryDate: '',
            NextDeliveryQty: 0,
            Price: '$0.01',
            graph: {
                FC: [
                    {wk: 'hist5', value: 3000},
                    {wk: 'hist4', value: 2500},
                    {wk: 'hist3', value: 2700},
                    {wk: 'hist2', value: 2600},
                    {wk: 'hist1', value: 3100},
                    {wk: 'wk1', value: 3200},
                    {wk: 'wk2', value: 3300},
                    {wk: 'wk3', value: 3100},
                    {wk: 'wk4', value: 3000},
                    {wk: 'wk5', value: 2900},
                ],
                SOLD: [
                    {wk: 'hist5', value: 3231},
                    {wk: 'hist4', value: 3330},
                    {wk: 'hist3', value: 3450},
                    {wk: 'hist2', value: 3400},
                    {wk: 'hist1', value: 3501},
                    {wk: 'wk1', value: 1543},
                    {wk: 'wk2', value: 0},
                    {wk: 'wk3', value: 0},
                    {wk: 'wk4', value: 0},
                    {wk: 'wk5', value: 0},
                ],
            }
        }
    },
    {
        ID: 4,
        ARTNO: 12348,
        info: {
            SLoc: 'interior 2',
            SSD: '2009-01-01',
            EDS: '2023-01-01',
            MDQ: 4,
            Stock: 40,
            NextDeliveryDate: '2022-04-05',
            NextDeliveryQty: 12,
            Price: '$20',
            graph: {
                FC: [
                    {wk: 'hist5', value: 15},
                    {wk: 'hist4', value: 11},
                    {wk: 'hist3', value: 12},
                    {wk: 'hist2', value: 11},
                    {wk: 'hist1', value: 10},
                    {wk: 'wk1', value: 9},
                    {wk: 'wk2', value: 11},
                    {wk: 'wk3', value: 10},
                    {wk: 'wk4', value: 10},
                    {wk: 'wk5', value: 12},
                ],
                SOLD: [
                    {wk: 'hist5', value: 14},
                    {wk: 'hist4', value: 10},
                    {wk: 'hist3', value: 5},
                    {wk: 'hist2', value: 5},
                    {wk: 'hist1', value: 7},
                    {wk: 'wk1', value: 22},
                    {wk: 'wk2', value: 0},
                    {wk: 'wk3', value: 0},
                    {wk: 'wk4', value: 0},
                    {wk: 'wk5', value: 0},
                ],
            }
        }
    },
    {
        ID: 5,
        ARTNO: 12349,
        info: {
            SLoc: 'shelf 2',
            SSD: '2009-01-01',
            EDS: '',
            MDQ: 100,
            Stock: 2,
            NextDeliveryDate: '2022-04-05',
            NextDeliveryQty: 300,
            Price: '$0.5',
            graph: {
                FC: [
                    {wk: 'hist5', value: 100},
                    {wk: 'hist4', value: 110},
                    {wk: 'hist3', value: 105},
                    {wk: 'hist2', value: 100},
                    {wk: 'hist1', value: 105},
                    {wk: 'wk1', value: 99},
                    {wk: 'wk2', value: 105},
                    {wk: 'wk3', value: 110},
                    {wk: 'wk4', value: 115},
                    {wk: 'wk5', value: 100},
                ],
                SOLD: [
                    {wk: 'hist5', value: 80},
                    {wk: 'hist4', value: 78},
                    {wk: 'hist3', value: 76},
                    {wk: 'hist2', value: 55},
                    {wk: 'hist1', value: 44},
                    {wk: 'wk1', value: 33},
                    {wk: 'wk2', value: 0},
                    {wk: 'wk3', value: 0},
                    {wk: 'wk4', value: 0},
                    {wk: 'wk5', value: 0},
                ],
            }
        }
    },
    {
        ID: 6,
        ARTNO: 12350,
        info: {
            SLoc: 'shelf 4',
            SSD: '2014-01-01',
            EDS: '',
            MDQ: 30,
            Stock: 50,
            NextDeliveryDate: '',
            NextDeliveryQty: 0,
            Price: '$5',
            graph: {
                FC: [
                    {wk: 'hist5', value: 13},
                    {wk: 'hist4', value: 15},
                    {wk: 'hist3', value: 11},
                    {wk: 'hist2', value: 12},
                    {wk: 'hist1', value: 11},
                    {wk: 'wk1', value: 14},
                    {wk: 'wk2', value: 16},
                    {wk: 'wk3', value: 18},
                    {wk: 'wk4', value: 15},
                    {wk: 'wk5', value: 18},
                ],
                SOLD: [
                    {wk: 'hist5', value: 15},
                    {wk: 'hist4', value: 18},
                    {wk: 'hist3', value: 21},
                    {wk: 'hist2', value: 22},
                    {wk: 'hist1', value: 25},
                    {wk: 'wk1', value: 12},
                    {wk: 'wk2', value: 0},
                    {wk: 'wk3', value: 0},
                    {wk: 'wk4', value: 0},
                    {wk: 'wk5', value: 0},
                ],
            }
        }
    },
    {
        ID: 7,
        ARTNO: 12351,
        info: {
            SLoc: 'interior 2',
            SSD: '2020-03-01',
            EDS: '',
            MDQ: 12,
            Stock: 33,
            NextDeliveryDate: '2022-03-20',
            NextDeliveryQty: 24,
            Price: '$50',
            graph: {
                FC: [
                    {wk: 'hist5', value: 21},
                    {wk: 'hist4', value: 22},
                    {wk: 'hist3', value: 23},
                    {wk: 'hist2', value: 21},
                    {wk: 'hist1', value: 20},
                    {wk: 'wk1', value: 18},
                    {wk: 'wk2', value: 16},
                    {wk: 'wk3', value: 17},
                    {wk: 'wk4', value: 19},
                    {wk: 'wk5', value: 16},
                ],
                SOLD: [
                    {wk: 'hist5', value: 20},
                    {wk: 'hist4', value: 25},
                    {wk: 'hist3', value: 21},
                    {wk: 'hist2', value: 19},
                    {wk: 'hist1', value: 21},
                    {wk: 'wk1', value: 11},
                    {wk: 'wk2', value: 0},
                    {wk: 'wk3', value: 0},
                    {wk: 'wk4', value: 0},
                    {wk: 'wk5', value: 0},
                ],
            }
        }
    },
    {
        ID: 8,
        ARTNO: 12352,
        info: {
            SLoc: 'fridge 1',
            SSD: '2020-07-01',
            EDS: '2020-05-01',
            MDQ: 8,
            Stock: 4,
            NextDeliveryDate: '2022-03-20',
            NextDeliveryQty: 16,
            Price: '$0.9',
            graph: {
                FC: [
                    {wk: 'hist5', value: 3},
                    {wk: 'hist4', value: 5},
                    {wk: 'hist3', value: 6},
                    {wk: 'hist2', value: 5},
                    {wk: 'hist1', value: 7},
                    {wk: 'wk1', value: 10},
                    {wk: 'wk2', value: 11},
                    {wk: 'wk3', value: 10},
                    {wk: 'wk4', value: 12},
                    {wk: 'wk5', value: 1},
                ],
                SOLD: [
                    {wk: 'hist5', value: 5},
                    {wk: 'hist4', value: 6},
                    {wk: 'hist3', value: 9},
                    {wk: 'hist2', value: 10},
                    {wk: 'hist1', value: 11},
                    {wk: 'wk1', value: 7},
                    {wk: 'wk2', value: 0},
                    {wk: 'wk3', value: 0},
                    {wk: 'wk4', value: 0},
                    {wk: 'wk5', value: 0},
                ],
            }
        }
    },
    {
        ID: 9,
        ARTNO: 12353,
        info: {
            SLoc: 'shelf 1',
            SSD: '2020-07-01',
            EDS: '2020-05-01',
            MDQ: 100,
            Stock: 1400,
            NextDeliveryDate: '',
            NextDeliveryQty: 0,
            Price: '$0.2',
            graph: {
                FC: [
                    {wk: 'hist5', value: 300},
                    {wk: 'hist4', value: 350},
                    {wk: 'hist3', value: 340},
                    {wk: 'hist2', value: 320},
                    {wk: 'hist1', value: 340},
                    {wk: 'wk1', value: 350},
                    {wk: 'wk2', value: 340},
                    {wk: 'wk3', value: 345},
                    {wk: 'wk4', value: 344},
                    {wk: 'wk5', value: 300},
                ],
                SOLD: [
                    {wk: 'hist5', value: 350},
                    {wk: 'hist4', value: 500},
                    {wk: 'hist3', value: 700},
                    {wk: 'hist2', value: 10},
                    {wk: 'hist1', value: 0},
                    {wk: 'wk1', value: 0},
                    {wk: 'wk2', value: 0},
                    {wk: 'wk3', value: 0},
                    {wk: 'wk4', value: 0},
                    {wk: 'wk5', value: 0},
                ],
            }
        }
    },
    {
        ID: 10,
        ARTNO: 12354,
        info: {
            SLoc: 'interior 2',
            SSD: '2021-07-01',
            EDS: '',
            MDQ: 1,
            Stock: 12,
            NextDeliveryDate: '2022-04-07',
            NextDeliveryQty: 0,
            Price: '$5',
            graph: {
                FC: [
                    {wk: 'hist5', value: 15},
                    {wk: 'hist4', value: 16},
                    {wk: 'hist3', value: 15},
                    {wk: 'hist2', value: 14},
                    {wk: 'hist1', value: 15},
                    {wk: 'wk1', value: 15},
                    {wk: 'wk2', value: 15},
                    {wk: 'wk3', value: 14},
                    {wk: 'wk4', value: 16},
                    {wk: 'wk5', value: 15},
                ],
                SOLD: [
                    {wk: 'hist5', value: 22},
                    {wk: 'hist4', value: 23},
                    {wk: 'hist3', value: 14},
                    {wk: 'hist2', value: 15},
                    {wk: 'hist1', value: 17},
                    {wk: 'wk1', value: 3},
                    {wk: 'wk2', value: 0},
                    {wk: 'wk3', value: 0},
                    {wk: 'wk4', value: 0},
                    {wk: 'wk5', value: 0},
                ],
            }
        }
    },
    {
        ID: 11,
        ARTNO: 12355,
        info: {
            SLoc: 'shelf 3',
            SSD: '2011-07-01',
            EDS: '',
            MDQ: 20,
            Stock: 1000,
            NextDeliveryDate: '',
            NextDeliveryQty: 0,
            Price: '$1.5',
            graph: {
                FC: [
                    {wk: 'hist5', value: 33},
                    {wk: 'hist4', value: 55},
                    {wk: 'hist3', value: 44},
                    {wk: 'hist2', value: 37},
                    {wk: 'hist1', value: 33},
                    {wk: 'wk1', value: 43},
                    {wk: 'wk2', value: 45},
                    {wk: 'wk3', value: 40},
                    {wk: 'wk4', value: 41},
                    {wk: 'wk5', value: 33},
                ],
                SOLD: [
                    {wk: 'hist5', value: 30},
                    {wk: 'hist4', value: 45},
                    {wk: 'hist3', value: 49},
                    {wk: 'hist2', value: 40},
                    {wk: 'hist1', value: 30},
                    {wk: 'wk1', value: 40},
                    {wk: 'wk2', value: 0},
                    {wk: 'wk3', value: 0},
                    {wk: 'wk4', value: 0},
                    {wk: 'wk5', value: 0},
                ],
            }
        }
    },
    {
        ID: 12,
        ARTNO: 12356,
        info: {
            SLoc: 'shelf 1',
            SSD: '2015-07-01',
            EDS: '',
            MDQ: 50,
            Stock: 120,
            NextDeliveryDate: '',
            NextDeliveryQty: 0,
            Price: '$0.3',
            graph: {
                FC: [
                    {wk: 'hist5', value: 100},
                    {wk: 'hist4', value: 110},
                    {wk: 'hist3', value: 120},
                    {wk: 'hist2', value: 110},
                    {wk: 'hist1', value: 105},
                    {wk: 'wk1', value: 108},
                    {wk: 'wk2', value: 110},
                    {wk: 'wk3', value: 115},
                    {wk: 'wk4', value: 120},
                    {wk: 'wk5', value: 125},
                ],
                SOLD: [
                    {wk: 'hist5', value: 99},
                    {wk: 'hist4', value: 120},
                    {wk: 'hist3', value: 126},
                    {wk: 'hist2', value: 99},
                    {wk: 'hist1', value: 130},
                    {wk: 'wk1', value: 80},
                    {wk: 'wk2', value: 0},
                    {wk: 'wk3', value: 0},
                    {wk: 'wk4', value: 0},
                    {wk: 'wk5', value: 0},
                ],

            }
        }
    },
]